apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
  namespace: healthmate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
        - name: patient-service
          image: healthmate/patient-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5002
          envFrom:
            - configMapRef:
                name: patient-service-config
                optional: true
            - secretRef:
                name: patient-service-secret
                optional: true
---
apiVersion: v1
kind: Service
metadata:
  name: patient-service
  namespace: healthmate
spec:
  selector:
    app: patient-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP
