apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
  namespace: healthmate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
        - name: appointment-service
          image: healthmate/appointment-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5004
          env:
            - name: PORT
              value: "5004"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: appointment-service-secret
                  key: MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: appointment-service-secret
                  key: JWT_SECRET
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:5001/api/auth"
            - name: DOCTOR_SERVICE_URL
              value: "http://doctor-service:5003/api/doctors"
            - name: NOTIFICATION_SERVICE_URL
              value: "http://notification-service:5006/api/notifications"
            - name: APPOINTMENT_INTERNAL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: appointment-service-secret
                  key: APPOINTMENT_INTERNAL_TOKEN
            - name: AUTH_INTERNAL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: appointment-service-secret
                  key: AUTH_INTERNAL_TOKEN
            - name: NOTIFICATION_INTERNAL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: appointment-service-secret
                  key: NOTIFICATION_INTERNAL_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: appointment-service
  namespace: healthmate
spec:
  selector:
    app: appointment-service
  ports:
    - name: http
      port: 5004
      targetPort: 5004
  type: ClusterIP
