apiVersion: apps/v1
kind: Deployment
metadata:
  name: prescription-service
  namespace: healthmate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prescription-service
  template:
    metadata:
      labels:
        app: prescription-service
    spec:
      containers:
        - name: prescription-service
          image: healthmate/prescription-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5008
          env:
            - name: PORT
              value: "5008"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: prescription-service-secret
                  key: MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: prescription-service-secret
                  key: JWT_SECRET
            - name: APPOINTMENT_SERVICE_URL
              value: "http://appointment-service:5004/api/appointments"
            - name: APPOINTMENT_INTERNAL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: prescription-service-secret
                  key: APPOINTMENT_INTERNAL_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: prescription-service
  namespace: healthmate
spec:
  selector:
    app: prescription-service
  ports:
    - name: http
      port: 5008
      targetPort: 5008
  type: ClusterIP
