apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: healthmate
type: Opaque
stringData:
  MONGO_URI: "mongodb://mongo:27017/healthmate-auth"
  JWT_SECRET: "replace-with-strong-jwt-secret"
  ACCESS_TOKEN_EXPIRES_IN: "7d"
