apiVersion: v1
kind: Secret
metadata:
  name: doctor-service-secret
  namespace: healthmate
type: Opaque
stringData:
  MONGO_URI: "mongodb://mongo:27017/healthmate-doctor"
  JWT_SECRET: "replace-with-strong-jwt-secret"
