apiVersion: v1
kind: Secret
metadata:
  name: appointment-service-secret
  namespace: healthmate
type: Opaque
stringData:
  MONGO_URI: "mongodb://mongo:27017/healthmate-appointment"
  JWT_SECRET: "replace-with-strong-jwt-secret"
  APPOINTMENT_INTERNAL_TOKEN: "replace-with-internal-token"
  AUTH_INTERNAL_TOKEN: "replace-with-internal-token"
  NOTIFICATION_INTERNAL_TOKEN: "replace-with-internal-token"
