apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: healthmate
resources:
  - 00-namespace.yaml
  - 10-auth-secret.yaml
  - 20-doctor-secret.yaml
  - 30-appointment-secret.yaml
  - 40-prescription-secret.yaml
  - 50-telemedicine-secret.yaml
  - 60-auth-service.yaml
  - 70-doctor-service.yaml
  - 80-appointment-service.yaml
  - 90-prescription-service.yaml
  - 95-telemedicine-service.yaml
  - 99-doctor-ingress.yaml
